### PR TITLE
Copy changes for state on October 30

### PR DESCRIPTION
**Pull request by jimwebb**
This is the beginning of copy changes to the dashboard on October 30 (the send date). There's a date check in there, so this should be OK to merge into production and won't have an effect on the pre-send-date copy. 

To test, change or add `REACT_APP_DATE_TO_SEND_LETTERS=2018-10-25`, replaced with the date of your choice, in `.env` and restart the app.

Right now this includes copy changes to the dashboard as copyedited by Nate Kaufman. It does *not* yet include a "congratulations" modal if the user marks all of their letters as sent. (I'm heading out of town for the weekend and wanted to get this to you before I went offline.)

### CODE REVIEW

**Comment by jimwebb** [comment]
This also includes commits from https://github.com/sjforman/votefwd/pull/263

**Comment by jimwebb** [comment]
@sjforman this is ready for your testing; here's a summary of changes to the UI on midnight of the send date (October 30, or however `REACT_APP_DATE_TO_SEND_LETTERS` is set in `.env`:

Dashboard changes if the user has letters to send:

image

Dashboard if the user has no letters to send:

image

Modal text changes for "Mark all letters as mailed:"

image

Congratulations message once all letters are marked as mailed:

image

On the send date, *all* districts are marked as completely adopted, no matter their actual state, and a small message is added to the home page list:

image

Thanks!

**Comment by jimwebb** [comment]
NOTE: This code will SHUT DOWN all new voter adoptions on the send date. If that's not the desired outcome, holler and I'll change.

**Comment by sjforman** [comment]
I just tested this locally, and I LOVE IT. The congratulations message in particular is a really nice touch. I'm going to make a few small copy-edits and then merge this. THANK YOU @jimwebb

**Comment by jimwebb** [comment]
I just pushed a commit that decouples the "send" date from the "shut down new adoptions" date. 

This means that today (October 30), folks can mark letters as sent, and they get the "Congratulations!" message when they're all done. But they can also continue to adopt new voters.

Tomorrow (October 31, or `REACT_APP_DATE_TO_STOP_ADOPTIONS` in `.env`), new adoptions are shut down.

Best of both worlds, and a slightly better experience today!

**Pull request merged**
