### PR TITLE
Secure API routes in general, and specifically /voters 

### PR DESCRIPTION
**Pull request by andrewjtimmons**

### CODE REVIEW

**Comment by andrewjtimmons** [comment]
### What?

Hack my way to getting a valid auth and api token in the same call and validate them for one api route.
This combines the auth call with the api call 

Doc on Api calls: https://auth0.com/docs/quickstart/spa/vanillajs/03-calling-an-api  

Doc on how to solve JWT error: https://community.auth0.com/t/unauthorizederror-jwt-malformed-in-express-js/7352

Sample code that I scooped for the checkJWT const in server.js: https://auth0.com/docs/quickstart/backend/nodejs/01-authorization  

### Why didn't I update every api?
Wanted to check on this flow with you

### testing
I tested on dev.  Probably other ways to test?  I would love if you tried this too scott locally on your machine

### Risk
High.  It could break all auth AND all apis.  A true mess.

**Comment by sjforman** [comment]
This is awesome, Andy. Thank you. It seems you figured it. 

I've been looking this morning, and, looks really good! Main / most important thing is, I can see that, indeed, the `/voters/` endpoint returns `401-unauthorized` if I don't include the `access_token` in the request. And if I do include it, things continue to work as normal.

Things I've noticed so far:

 * Although it does work, I do get a new `500` error. 
screenshot 2018-06-27 12 18 07

Not sure the source of this, investigating. Any thoughts @andrewjtimmons? Do you see that too? 

 * The signup process now has this second screen where the user is prompted to grant the application access to the "tenant". No big deal if this is unavoidable, but it's a bit odd. Looking to see if there's a setting that makes this skippable.  
screenshot 2018-06-27 11 54 26

**Comment by andrewjtimmons** [comment]
Weird about that 500 error, I could have sworn it was getting voters.  Let me debug

**Comment by andrewjtimmons** [comment]
It was that tricky env var.  This example on the api page autofills but the one i got somewhere else did not autofill the url so my env had some #magic

**Comment by sjforman** [comment]
Ah! That explains it. Ok. I suppose I can see why one might want to make that an environment variable, in case it changes at some point. But change seems unlikely, so, yeah, all good.

I think those two environment variables still needed to be set a few lines farther south in `checkJwt`, just pushed that change.

**Comment by sjforman** [comment]
Ok, I was able to deploy this to staging and confirm that, a) things still work, and b) user not prompted to grant access to the API "tenant." So, yeah, good stuff!

I think there's one remaining step which is to secure the other routes. I think they should all be secure except "pledge," since that's the one we want users to be able to hit without authenticating.

**Comment by sjforman** [comment]
I'll go ahead and merge this, and secure the other routes in a separate commit.

**Pull request merged**
