### PR TITLE
Email reminders

### PR DESCRIPTION
**Pull request by asterns**
Allows admin to download target lists of emails.  To use, go to /admin/users.  You'll see three lists: 
- None Prepped - users who have adopted voters and haven't prepped any
- Some Prepped - users who have adopted voters and have prepped some but not all
- Some Not Sent - users who have some letters not yet sent

### CODE REVIEW

**Comment by jimwebb** [comment]
@asterns Does the list of users generated by this code accidentally include users who are marked as "banned" or "pre-qualified"? If so, it might explain a few of the help desk tickets we've been getting.

**Comment by asterns** [comment]
Yes, those users are included. I can fix it later tonight.

**Comment by asterns** [comment]
Wait @sjforman, have you sent these emails yet? I didn't receive one, and I'm a user who hasn't marked all my letters as completed...

**Comment by asterns** [comment]
@jimwebb, do you mind taking a look at the query once I correct it to make sure I'm not missing any other criteria?

**Comment by sjforman** [comment]
Hello friends! 

Update is, I wanted to get this done ASAP and I found that this output didn't *quite* fit the bill as I was actually trying to get the data into Mailchimp and handle the merge tags, so I hand-crafted (possibly buggy) alternatives and ran them manually against the database. I did in fact send the emails, to two lists: 

1. "Qualified users who hadn't adopted any voters yet": 
```sql
SELECT u.created_at                 AS created_at, 
       email, 
       full_name, 
       u.zip                        AS zip, 
       Split_part(auth0_id, '|', 1) AS identity_provider 
FROM   users u 
       LEFT JOIN voters v 
              ON u.auth0_id = v.adopter_user_id 
WHERE  v.adopter_user_id IS NULL 
       AND u.email IS NOT NULL 
       AND email NOT IN (SELECT email 
                         FROM   users 
                         WHERE  email IS NOT NULL 
                         GROUP  BY email 
                         HAVING Count(*) > 1) 
       AND qual_state = 'qualified'; 
```

2. "Qualified users with at least one voter not yet marked "prepped"": 
```sql
SELECT u.created_at                 AS created_at, 
       email, 
       full_name, 
       u.zip                        AS zip, 
       Split_part(auth0_id, '|', 1) AS identity_provider, 
       Count(*) 
FROM   users u 
       LEFT JOIN voters v 
              ON u.auth0_id = v.adopter_user_id 
WHERE  v.adopter_user_id IS NOT NULL 
       AND u.email IS NOT NULL 
       AND u.email NOT IN (SELECT email 
                           FROM   users 
                           WHERE  email IS NOT NULL 
                           GROUP  BY email 
                           HAVING Count(*) > 1) 
       AND qual_state = 'qualified' 
       AND confirmed_prepped_at IS NULL 
       AND confirmed_sent_at IS NULL 
GROUP  BY u.created_at, 
          email, 
          full_name, 
          u.zip, 
          identity_provider; 
```

What would really make this easiest over the coming days and weeks would be if there were any easy way to pull the following out of the database and into Mailchimp: 

 * email address
 * Indicator of whether the email address is a duplicate
 * Just the "qualified" and "super-qualified" users (I forgot to include "super-qualified" people in the second query, above). 
 * Qualification state
 * number "adopted" 
 * number "prepped"
 * number "sent"  
 * ZIP code
 * Full name
 * Created_at date
 * "identity provider" (`auth0`, `google-oauth2`, or `facebook`) (in case of duplicates, perhaps include multiple / all, in separate columns? That SQL would be way beyond me, which is why I just excluded these entirely, and that would also be fine. Or just "multiple" as the value for ID provider in case of duplicates).

By getting all these counts into MC, I should be able to construct audiences / segments for all the different emails we want to send, and also include the requisite dynamic content. 

If you're up for it @asterns  (and with apologies that I under-specified this before), could you help me construct this? It doesn't necessarily need to be in the application itself, could just be SQL. 

THANK YOU!

**Comment by asterns** [comment]
Yes I can take care of that tonight! Do you mind sending me one of the emails through mail chimp to see if it ends up in my promotion tab?

**Comment by sjforman** [comment]
(just sent test to you, BTW — will be curious to know where it landed) 
Thank you!!

**Comment by asterns** [comment]
It landed in my main inbox, thanks!

**Pull request merged**
