### PR TITLE
New signup

### PR DESCRIPTION
**Pull request by heyitsgarrett**
New signup flow! 
- Adds new /verify route and moves qualification steps there
- Adds new form fields for verifying the intent of the volunteer
- Scott is a meat popsicle

### CODE REVIEW

**Comment by heyitsgarrett** [comment]
Okay, made a few more changes:
- Added a new /utils folder, mainly for User checks but will be useful in the future. This isolates data model checks in case we need to update anything in the future.
- Cleaned up a bunch of the Qualification, moved `isQualified` to the new Utils area
- Cleaned up the CSS, made some improvements to the buttons.

Going to be tackling /admin next, but this should be good to go!

**Comment by sjforman** [comment]
At quick glance, this looks awesome. I will review more closely soon, but I probably won't merge until after Tuesday, to avoid unexpected hiccups in the last few days of letter-writing before OH-12.

**Comment by heyitsgarrett** [comment]
Sounds great, I'm going to keep working on admin on this same branch in the meantime

**Comment by sjforman** [comment]
MERGING!!!! Thank you!!

**Pull request merged**
