### PR TITLE
Adds Google Analytics tracking

### PR DESCRIPTION
**Pull request by jeffkole**
Addresses issue #143

### CODE REVIEW

**Comment by jeffkole** [comment]
You'll need to set the `REACT_APP_GA_TRACKING_ID` environment variable to get it working, but it appears to work great from my local testing.

**Comment by sjforman** [comment]
Awesome — THANK YOU!! I thought that example looked pretty nicely done, but I wasn't 100% sure, so, really appreciate you taking a look, incorporating, and testing this.

**Comment by sjforman** [comment]
Ah, the debug flag, beautiful. 

Thank you, @yangshun and all contributors to https://github.com/react-ga/react-ga.

**Comment by sjforman** [comment]
Closes #143

**Pull request merged**
